networks:
  docker_web:
    driver: ${NETWORKS_DRIVER}
volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}
services:

### PHP-FPM ##############################################
    php-fpm:
      image: registry.cn-hangzhou.aliyuncs.com/fengdejiyi/php74:v1
#      build:
#        context: ./php-fpm
      volumes:
        - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        - ${APP_CODE_PATH_HOST}/selfstart/supervisord.d:/etc/supervisord.d
      expose:
        - "9000"
      environment:
        - DOCKER_TLS_VERIFY=1
        - DOCKER_TLS_CERTDIR=/certs
        - DOCKER_CERT_PATH=/certs/client
      networks:
        - docker_web
### NGINX Server #########################################
    nginx:
      image:  registry.cn-hangzhou.aliyuncs.com/fengdejiyi/nginx:v1
#      build:
#        context: ./nginx
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        - ${NGINX_SSL_PATH}:/etc/nginx/ssl
        - ${NGINX_CONFD_PATH}:/etc/nginx/conf.d/
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      depends_on:
        - php-fpm
      networks:
        - docker_web
