version: '3'

services:
  php74:
    container_name: php74-container_6
    image: registry.cn-hangzhou.aliyuncs.com/fengdejiyi/php74:v1
    volumes:
      - /home/www:/var/www
    ports:
      - "9000:9000"
    networks:
      - laradock_backend

networks:
  laradock_backend:
    name: laradock_backend  # 注意此处为 2 个空格
    driver: bridge

